# Generated by Django 4.2.11 on 2025-03-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='education_level',
            new_name='educational_level',
        ),
    ]
