# Generated by Django 5.1.2 on 2025-03-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='students', to='Students.subject'),
        ),
    ]
