# Generated by Django 4.2.11 on 2025-03-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educator',
            name='expertise',
        ),
        migrations.AddField(
            model_name='educator',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educator',
            name='subject_specialization',
            field=models.CharField(default='', max_length=255),
        ),
    ]
