# Generated by Django 5.1.1 on 2025-03-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="subject",
            field=models.CharField(default="General", max_length=100),
        ),
    ]
